spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:example@localhost:27017/memeland-user?authSource=admin}
springdoc.swagger-ui.path=/user.html
server.port=8080
spring.application.name=users

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
spring.cloud.discovery.enabled=${SPRING_CLOUD_DISCOVERY_ENABLED:true}
